### ISSUE TITLE
Need to update README to add proper instructions to get started for someone new to this NGIAB_data_preprocess

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB_data_preprocess#10]

**Comment by ZacharyWills** [comment]
As a note the Hydrofabric link in the readme is broken, should be: https://lynker-spatial.s3.amazonaws.com/hydrofabric/v20.1/conus.gpkg

**Comment by JoshCu** [comment]
Hydrofabric link is updated now and the readme hopefully has enough detail to get started without being overwhelming now.
