### ISSUE TITLE
sqlite3.OperationalError: no such table: main.divides

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB_data_preprocess#11]
While running run.sh using VScode on my local machine seeing below error:

  File "/Users/apatel54/Documents/Arpita/git/NGIAB_data_preprocess/data_processing/gpkg_utils.py", line 34, in verify_indices
    con.execute(index)
sqlite3.OperationalError: no such table: main.divides

![image](https://github.com/AlabamaWaterInstitute/NGIAB_data_preprocess/assets/54657/d65d488e-604f-440a-bfbc-7e381acd4fa9)

**Comment by jameshalgren** [comment]
The application is looking for a table in the conus.gpkg file. @chp2001, we might need to update the instructions (step 5, as the steps are currently laid out, should be in front of step 3.)

**Comment by JoshCu** [comment]
#22 Added code to automatically download these two files on first launch of the app which should mitigate this issue.
