### ISSUE TITLE
Server internal error

### ISSUE THREAD

**Issue by jmframe** [CIROH-UA/NGIAB_data_preprocess#20]
I've been trying to get the data processing to work, and I've tried on several different computers. Below is the most recent error. It occurs when trying to "Create subset gpkg" for wb-3315280, if that at all matters.

From WSL (Ubuntu):
```
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

In the output directory a folder is made for wb-3315280, and `cfe_noahowp_attributes.csv` gets created, and that looks correct, but the sub-directory `config` is empty, and no other sub-directories or files are made.

Any ideas?

**Comment by JoshCu** [comment]
It looks like the web server has unhelpfully hidden the actual python error, but it's probably one of two things.
1. part of the subsetting process calls the `ogr2ogr` command line tool, so if that's not available on the wsl cli then that could break it
2. There are some issues creating subsets for catchments that flow into a coastal nexus. It's hard to say without the exact conus.gpkg you're using, but for me, wb-3315280 is not coastal and the subset worked.
![image](https://github.com/CIROH-UA/NGIAB_data_preprocess/assets/26720477/8f06d66b-96ba-4491-9e69-c5653a530171)

So to trouble shoot I'd:

1. Check the `ogr2ogr` command works in wsl, if not `sudo apt install gdal-bin` should install it
2. Delete `conus.gpickle` in the data sources folder and restart the app (this file is the network graph and needs to be regenerated if the conus.gpkg is ever changed
3. Try reinstalling the tool from scratch. I recently updated it and published it to pypi, so you can just do 
```bash
pip install ngiab_data_preprocess
python -m map_app
```
and the first time it's run, it will automatically re-download the conus gpkg
