### ISSUE TITLE
Add Lynker attribution to Map byline

### ISSUE THREAD

**Issue by jameshalgren** [CIROH-UA/NGIAB_data_preprocess#4]
This...
![image](https://github.com/AlabamaWaterInstitute/NGIAB_data_preprocess/assets/53343824/1a86f8d7-a0a2-4a5a-8308-1a8df377dc3e)
...should probably include attribution for the use of material from the Lynker repository, as noted here: 
https://lynker-spatial.s3.amazonaws.com/copyright.html

**Comment by JoshCu** [comment]
well overdue
just fixed it
https://github.com/CIROH-UA/NGIAB_data_preprocess/commit/b2047bc659d02a8b2c5a4d18103de93248b5e80b
