### ISSUE TITLE
README Steps for mac needs update

### ISSUE THREAD

**Issue by arpita0911patel** [CIROH-UA/NGIAB_data_preprocess#52]
Command that worked on mac:
 pip install 'ngiab_data_preprocess[plot]'

**Comment by JoshCu** [comment]
https://github.com/CIROH-UA/NGIAB_data_preprocess/commit/d925a131a183be4ec6c60c1733ff30a4148652ea

Just updated them, as well as removing some of the requirements that are no longer needed
