### ISSUE TITLE
 Hide/Show Console Button Overlaps Create Realization Button

### ISSUE THREAD

**Issue by imanmaghami** [CIROH-UA/NGIAB_data_preprocess#59]
The Hide/Show Console button currently overlaps with the Create Realization button when the Console is shown. It would be great to avoid this overlap so that even if the Console is shown, the Create Realization button is not covered. Please see the screenshots attached below for the behavior:
![image](https://github.com/user-attachments/assets/8b90b137-d7e8-4bcd-b19b-e7c3abf0ec43)
![image](https://github.com/user-attachments/assets/f7929446-7b40-45da-907d-90fa9acc0278)

**Comment by JoshCu** [comment]
This should be resolved by #61 and in release v3.0.3.
The fix I used extends the page when that button is clicked rather than just adding a huge white space to the bottom. The dynamic resizing can be a bit inconsistent so if it's not working I'll change it to just be a constant extra bit of space.
