### ISSUE TITLE
Disable map interaction when clicking legend

### ISSUE THREAD

**Issue by chp2001** [CIROH-UA/NGIAB_data_preprocess#7]
Toggling layers via legend buttons is causing zooming in/out when undesired. Very inconvenient when trying to change the visuals without moving the frame.
Should be fixable by intercepting the click event on the legend element.

**Comment by JoshCu** [comment]
is this not working? https://github.com/AlabamaWaterInstitute/NGIAB_data_preprocess/blob/d3638df628ccf2b5bb86472a74ae163c5553cccb/map_app/static/js/legend.js#L36

**Comment by JoshCu** [comment]
I think this is fixed?
